language: cpp
sudo: required
dist: trusty
notifications:
  on_success: change
  on_failure: always
  on_start: false

matrix:
  include:
    - os: linux
      env: CC=gcc-4.9 CXX=g++-4.9
      addons: &gcc49
        apt:
          packages:
            - libstdc++-5-dev
          sources:
            - ubuntu-toolchain-r-test
      install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq g++-4.9

    - os: linux
      env: CC=gcc-5 CXX=g++-5
      addons: &gcc5
        apt:
          packages:
            - g++-5
            - libstdc++-5-dev
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: CC=clang-3.5 CXX=clang++-3.5
      addons: &clang35
        apt:
          packages:
            - clang-3.5
          sources:
            - llvm-toolchain-precise-3.5
            - ubuntu-toolchain-r-test
      install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq g++-4.9

    - os: linux
      env: CC=clang-3.6 CXX=clang++-3.6
      addons: &clang36
        apt:
          packages:
            - clang-3.6
          sources:
            - llvm-toolchain-precise-3.6
            - ubuntu-toolchain-r-test
      install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq g++-4.9

before_install:
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then git clone --recursive https://github.com/boostorg/boost.git; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pushd "boost"; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pushd "libs"; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then git clone https://github.com/olk/boost-fiber.git fiber; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then popd; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./bootstrap.sh --prefix=/usr/local/boost_head --with-libraries=fiber,context,thread,date_time,filesystem,system,program_options,test; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./b2 headers; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo ./b2 cxxflags="-std=c++11 -fPIC" threading=multi link=static install; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then popd; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then git clone https://github.com/tatsuhiro-t/nghttp2.git; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pushd "nghttp2"; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then autoreconf -i && automake && autoconf; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./configure --with-boost=/usr/local/boost_head --enable-asio-lib; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo make install; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then popd; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then curl http://www.lua.org/ftp/lua-5.3.2.tar.gz | tar xz; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pushd "lua-5.3.2"; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then make linux CC="g++ -std=c++11"; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo make install; fi

script:
  - mkdir build && cd build
  - cmake -DBOOST_ROOT=/usr/local/boost_head ..
  - export CTEST_OUTPUT_ON_FAILURE=TRUE
  - make && ctest
